prog_articles/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.articles_list, name='articles_list')
]

prog_articles/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

prog_articles/prog_articles/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('articles/', include('articles.urls', namespace='articles'))
]

prog_articles/articles/models.py
from django.db import models

# Create your models here.

prog_articles/home/models.py
from django.db import models

# Create your models here.

prog_articles/articles/views.py
from django.shortcuts import render


def articles_list(request):
    return render(request, 'articles/list.html')

prog_articles/home/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home/home.html')

prog_articles/articles/templates/articles/list.html
{% extends 'home/base.html' %}
{% block title %}Статті{% endblock %}

{% block content %}
    <main>
        <p>Статті</p>
    </main>
{% endblock %}

prog_articles/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
</head>
<body>
    <header>
        <nav class="navbar">
            <ul>
                <li>
                    <a href="{% url 'home:home' %}">Домівка</a>
                </li>
                <li>
                    <a href="{% url 'articles:articles_list' %}">Статті</a>
                </li>
            </ul>
        </nav>
    </header>
    {% block content %}
        <main></main>
    {% endblock %}
</body>
</html>

prog_articles/home/templates/home/home.html
{% extends 'home/base.html' %}
{% block title %}Домівка{% endblock %}

{% block content %}
    <main>
        <p>Домівка</p>
    </main>
{% endblock %}